#!/bin/bash
function updatef()
{
	if echo "$updateq" | grep -iq "^y" ;then
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get autoremove
    sudo apt-get autoclean
		echo "updated"
	else
		clear
		echo "did not update"
	fi
	clear
}
