function f_aide {

  sudo apt-get install aide -y
  sudo aideinit
  sudo cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  sudo update-aide.conf
  sudo cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf

}
