function f_aide {
  echo -n "Installing and Configuring AIDE... "

  sudo apt-get install aide
  sudo aideinit
  sudo cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  sudo update-aide.conf
  sudo cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf

  echo "[COMPLETE]"

}
