function f_php {

    apt-get install php5-suhosin -y

    grep -q '^safe_mode' /etc/php5/apache2/php.ini && sed -i 's/^safe_mode.*/safe_mode = On/' /etc/php5/apache2/php.ini || echo 'safe_mode = On' >> /etc/php5/apache2/php.ini
    grep -q '^safe_mode_gid' /etc/php5/apache2/php.ini && sed -i 's/^safe_mode_gid.*/safe_mode_gid = On/' /etc/php5/apache2/php.ini || echo 'safe_mode_gid = On' >> /etc/php5/apache2/php.ini
    grep -q '^register_globals' /etc/php5/apache2/php.ini && sed -i 's/^register_globals.*/register_globals = Off/' /etc/php5/apache2/php.ini || echo 'register_globals = Off' >> /etc/php5/apache2/php.ini
    grep -q '^expose_php' /etc/php5/apache2/php.ini && sed -i 's/^expose_php.*/expose_php = Off/' /etc/php5/apache2/php.ini || echo 'expose_php = Off' >> /etc/php5/apache2/php.ini
    grep -q '^track_errors' /etc/php5/apache2/php.ini && sed -i 's/^track_errors.*/track_errors = Off/' /etc/php5/apache2/php.ini || echo 'track_errors = Off' >> /etc/php5/apache2/php.ini
    grep -q '^html_errors' /etc/php5/apache2/php.ini && sed -i 's/^html_errors.*/html_errors = Off/' /etc/php5/apache2/php.ini || echo 'html_errors = Off' >> /etc/php5/apache2/php.ini
    grep -q '^display_errors' /etc/php5/apache2/php.ini && sed -i 's/^display_errors.*/display_errors = Off/' /etc/php5/apache2/php.ini || echo 'display_errors = Off' >> /etc/php5/apache2/php.ini
    grep -q '^allow_url_fopen' /etc/php5/apache2/php.ini && sed -i 's/^allow_url_fopen.*/allow_url_fopen = Off/' /etc/php5/apache2/php.ini || echo 'allow_url_fopen = Off' >> /etc/php5/apache2/php.ini
    grep -q '^disable_functions' /etc/php5/apache2/php.ini && sed -i 's/^disable_functions.*/disable_functions = php_uname, getmyuid, getmypid, passthru, leak, listen, diskfreespace, tmpfile, link, ignore_user_abord, shell_exec, dl, set_time_limit, exec, system, highlight_file, source, show_source, fpaththru, virtual, posix_ctermid, posix_getcwd, posix_getegid, posix_geteuid, posix_getgid, posix_getgrgid, posix_getgrnam, posix_getgroups, posix_getlogin, posix_getpgid, posix_getpgrp, posix_getpid, posix, _getppid, posix_getpwnam, posix_getpwuid, posix_getrlimit, posix_getsid, posix_getuid, posix_isatty, posix_kill, posix_mkfifo, posix_setegid, posix_seteuid, posix_setgid, posix_setpgid, posix_setsid, posix_setuid, posix_times, posix_ttyname, posix_uname, proc_open, proc_close, proc_get_status, proc_nice, proc_terminate, phpinfo/' /etc/php5/apache2/php.ini || echo 'disable_functions = php_uname, getmyuid, getmypid, passthru, leak, listen, diskfreespace, tmpfile, link, ignore_user_abord, shell_exec, dl, set_time_limit, exec, system, highlight_file, source, show_source, fpaththru, virtual, posix_ctermid, posix_getcwd, posix_getegid, posix_geteuid, posix_getgid, posix_getgrgid, posix_getgrnam, posix_getgroups, posix_getlogin, posix_getpgid, posix_getpgrp, posix_getpid, posix, _getppid, posix_getpwnam, posix_getpwuid, posix_getrlimit, posix_getsid, posix_getuid, posix_isatty, posix_kill, posix_mkfifo, posix_setegid, posix_seteuid, posix_setgid, posix_setpgid, posix_setsid, posix_setuid, posix_times, posix_ttyname, posix_uname, proc_open, proc_close, proc_get_status, proc_nice, proc_terminate, phpinfo' >> /etc/php5/apache2/php.ini
    grep -q '^allow_url_include' /etc/php5/apache2/php.ini && sed -i 's/^allow_url_include.*/allow_url_include = Off/' /etc/php5/apache2/php.ini || echo 'allow_url_include = Off' >> /etc/php5/apache2/php.ini
    grep -q '^file_uploads' /etc/php5/apache2/php.ini && sed -i 's/^file_uploads.*/file_uploads = Off/' /etc/php5/apache2/php.ini || echo 'file_uploads = Off' >> /etc/php5/apache2/php.ini
    grep -q '^upload_max_filesize' /etc/php5/apache2/php.ini && sed -i 's/^upload_max_filesize.*/upload_max_filesize = 2M/' /etc/php5/apache2/php.ini || echo 'upload_max_filesize = 2M' >> /etc/php5/apache2/php.ini
    grep -q '^max_execution_time' /etc/php5/apache2/php.ini && sed -i 's/^max_execution_time.*/max_execution_time = 10/' /etc/php5/apache2/php.ini || echo 'max_execution_time = 10' >> /etc/php5/apache2/php.ini
    grep -q '^max_input_time' /etc/php5/apache2/php.ini && sed -i 's/^max_input_time.*/max_input_time = 30/' /etc/php5/apache2/php.ini || echo 'max_input_time = 30' >> /etc/php5/apache2/php.ini
    grep -q '^memory_limit' /etc/php5/apache2/php.ini && sed -i 's/^memory_limit.*/memory_limit = 40M/' /etc/php5/apache2/php.ini || echo 'memory_limit = 40M' >> /etc/php5/apache2/php.ini
    grep -q '^post_max_size' /etc/php5/apache2/php.ini && sed -i 's/^post_max_size.*/post_max_size=1K/' /etc/php5/apache2/php.ini || echo 'post_max_size=1K' >> /etc/php5/apache2/php.ini
    grep -q '^session.cookie_httponly' /etc/php5/apache2/php.ini && sed -i 's/^session.cookie_httponly.*/session.cookie_httponly = 1/' /etc/php5/apache2/php.ini || echo 'session.cookie_httponly = 1' >> /etc/php5/apache2/php.ini
    grep -q '^magic_quotes_gpc' /etc/php5/apache2/php.ini && sed -i 's/^magic_quotes_gpc.*/magic_quotes_gpc = Off/' /etc/php5/apache2/php.ini || echo 'magic_quotes_gpc = Off' >> /etc/php5/apache2/php.ini
    grep -q '^extension' /etc/php5/apache2/php.ini && sed -i 's/^extension.*/extension=suhosin.so/' /etc/php5/apache2/php.ini || echo 'extension=sudosin.so' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.session.encrypt' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.session.encrypt.*/suhosin.session.encrypt = Off/' /etc/php5/apache2/php.ini || echo 'suhosin.session.encrypt = Off' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.log.syslog' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.log.syslog.*/suhosin.log.syslog/' /etc/php5/apache2/php.ini || echo 'suhosin.log.syslog=511' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.executor.include.mix_traversal' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.executor.include.mix_traversal.*/suhosin.executor.include.mix_traversal=4/' /etc/php5/apache2/php.ini || echo 'suhosin.executor.include.mix_traversal=4' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.executor.disable_eval' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.executor.disable_eval.*/suhosin.executor.disable_eval=On/' /etc/php5/apache2/php.ini || echo 'suhosin.executor.disable_eval=On' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.executor.disable_emodifier' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.executor.disable_emodifier.*/suhosin.executor.disable_emodifier=On/' /etc/php5/apache2/php.ini || echo 'suhosin.executor.disable_emodifier=On' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.mail.protect' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.mail.protect.*/suhosin.mail.protect=2/' /etc/php5/apache2/php.ini || echo 'suhosin.mail.protect=2' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.sql.bailout_on_error' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.sql.bailout_on_error.*/suhosin.sql.bailout_on_error=On/' /etc/php5/apache2/php.ini || echo 'suhosin.sql.bailout_on_error=On' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.cookie.max_vars' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.cookie.max_vars.*/suhosin.cookie.max_vars = 2048/' /etc/php5/apache2/php.ini || echo 'suhosin.cookie.max_vars = 2048' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.get.max_array_index_length' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.get.max_array_index_length.*/suhosin.get.max_array_index_length = 256/' /etc/php5/apache2/php.ini || echo 'suhosin.get.max_array_index_length = 256' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.post.max_array_index_length' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.post.max_array_index_length.*/suhosin.post.max_array_index_length = 256/' /etc/php5/apache2/php.ini || echo 'suhosin.post.max_array_index_length = 256' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.post.max_totalname_lengt' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.post.max_totalname_lengt.*/suhosin.post.max_totalname_length = 8192/' /etc/php5/apache2/php.ini || echo 'suhosin.post.max_totalname_length = 8192' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.post.max_vars' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.post.max_vars.*/suhosin.post.max_vars = 2048/' /etc/php5/apache2/php.ini || echo 'suhosin.post.max_vars = 2048' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.request.max_totalname_length' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.request.max_totalname_length.*/suhosin.request.max_totalname_length = 8192/' /etc/php5/apache2/php.ini || echo 'suhosin.request.max_totalname_length = 8192' >> /etc/php5/apache2/php.ini
    grep -q '^suhosin.request.max_varname_length' /etc/php5/apache2/php.ini && sed -i 's/^suhosin.request.max_varname_length.*/suhosin.request.max_varname_length = 256/' /etc/php5/apache2/php.ini || echo 'suhosin.request.max_varname_length = 256' >> /etc/php5/apache2/php.ini
    
}